services:
#  auth-service:
#    build: .
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-mixtura}
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_USER: ${REDIS_USER:-default}
#      REDIS_PASSWORD: ${REDIS_PASSWORD:-default}
#      SMTP_USER: ${SMTP_USER}
#      SMTP_PASSWORD: ${SMTP_PASSWORD}
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./.local/mixtura-auth:/mixtura-auth/.local

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mixtura-auth}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.local/postgres:/var/lib/postgresql/data
      - ./alembic/versions:/mixtura-auth/alembic/versions
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_USER: ${REDIS_USER:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-default}
    ports:
      - "6379:6379"
    volumes:
      - ./.local/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5